### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (Reading 'length')

### ISSUE THREAD

**Issue by Janno117** [ArduPilot/WebTools#60] opened 2023-10-11 13:16 UTC
I have created a log file with ArduCopter V4.5.0-dev (1036244c) on Matek H743 SLIM v3.

When I try to load my log, I get following error message:

"Uncaught TypeError: Cannot read properties of undefined (reading 'length')
URL: https://firmware.ardupilot.org/Tools/FilterRevies/FilterReview.js
Line Number: 1632"

I tried to reload the page, I also tried entirely different browsers to ensure the cache is clear.

Screenshot of the original error message and the log I tried to load are included below.
![Filter_Review_Tool_Error_Message](https://github.com/ArduPilot/WebTools/assets/144016944/f58f6247-6977-445e-bcef-ee5cabd1577c)
LOG: https://we.tl/t-gA0Gkcke29

**Comment by IamPete1** [comment] 2023-10-13 00:25
Closed by https://github.com/ArduPilot/WebTools/pull/63.

The problem is just the big gaps in the log. Once the patch goes live you can turn down the window size to get some results, but not enough that the averaging is really working. 

Your flight controller should be able to keep up with the logging rate, it might be worth seeing if a nicer SD card helps. If not batch logging is a much more manageable logging rate so you might have better luck with that.

There are some new logging options coming to AP with the `INS_RAW_LOG_OPT` which gives raw logging but only one gyro for a much reduced logging rate.

**Closed by IamPete1** 2023-10-13 00:25 UTC

**Comment by amilcarlucas** [comment] 2023-10-14 13:24
Thanks for fixing this.

@Janno117 please open a new report with the stuff we discussed. This one is closed now.
